# -*- ruby -*-

$LOAD_PATH << './lib'
require 'rjack-jetty-jsp/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.2.0'
require 'rjack-tarpit'

include RJack

t = TarPit.new( 'rjack-jetty-jsp',
                Jetty::Jsp::VERSION,
                :jars_from_assembly, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps << [ 'rjack-jetty', "~> #{Jetty::Jsp::JETTY_VERSION}.0" ]
  h.rubyforge_name  = 'rjack'
  h.remote_rdoc_dir = 'jetty-jsp'
end

file 'webapps/test.war' => [ 'webapps/test/index.jsp',
                             'webapps/test/WEB-INF/web.xml' ] do
  sh( 'jar cvf webapps/test.war ' +
      '-C webapps/test index.jsp -C webapps/test WEB-INF/web.xml' )
end

t.generated_files = 'webapps/test.war'

t.assembly_version = 1.0

task :check_pom_deps do
  v = "#{ Jetty::Jsp::JETTY_VERSION }.#{ Jetty::Jsp::JETTY_BUILD }"
  t.test_line_match( 'pom.xml', %r{<version>#{ v }</version>} )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_deps, :check_history_version                      ]
task :tag  => [ :check_pom_deps, :check_history_version, :check_history_date ]
task :push => [                                          :check_history_date ]

t.define_tasks
