# -*- ruby -*-

source 'https://rubygems.org'

# Special case: If referenced this gemspec, bundler would use self as
# the rjack-maven impl. for rjack-tarpit, which has ordering issues.
# gemspec :name => 'rjack-maven'

# Instead specify separately
gem 'rjack-tarpit', '~> 2.0'
gem 'minitest',     '~> 4.7.4',     :group => :development
gem 'rdoc',         '~> 4.0.1',     :group => :development
