# -*- ruby -*-
source :rubygems
gemspec :path => '.', :name => 'rjack-commons-dbutils'

RJack::TarPit.last_spec.dependencies.each do |d|
  if d.name =~ /^rjack-(.+)$/ && ! %w[ tarpit maven ].include?( $1 )
    gem( d.name, :path => "../#{$1}" )
  end
end
