# -*- ruby -*-

$LOAD_PATH << './lib'
require 'rjack-httpclient-3/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.2.0'
require 'rjack-tarpit'

include RJack

t = TarPit.new( 'rjack-httpclient-3', HTTPClient3::VERSION, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps     += [ [ 'rjack-slf4j',         '~> 1.5.8' ],
                        [ 'rjack-commons-codec', '~> 1.4.0' ] ]
  h.extra_dev_deps <<   [ 'rjack-logback',       '>= 0.9.17' ]
  h.rubyforge_name = "rjack"
  h.remote_rdoc_dir = "httpclient-3"
end

t.jars = [ "commons-httpclient-#{ HTTPClient3::HTTPCLIENT_VERSION }.jar" ]

t.assembly_version = 1.0

file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

task :check_pom_deps do
  t.test_line_match( 'pom.xml',
                     %r[<version>#{ HTTPClient3::HTTPCLIENT_VERSION }</version>] )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_deps, :check_history_version                      ]
task :tag  => [ :check_pom_deps, :check_history_version, :check_history_date ]
task :push => [                                          :check_history_date ]

t.define_tasks
