# -*- ruby -*-

require 'rubygems'
require 'bundler/setup'
require 'rjack-tarpit'

RJack::TarPit.new( 'rjack-jdbc-postgres' ).define_tasks

%w[ 41 42 ].each do |v|
  jar = "postgresql-#{RJack::JDBCPostgres::DRIVER_VERSION}.jdbc#{v}.jar"
  file "lib/rjack-jdbc-postgres/#{jar}" do |t|
    sh "curl -sf -o #{t.name} https://jdbc.postgresql.org/download/#{jar}"
  end
end

desc "Upload RDOC to Amazon S3 (rdoc.gravitext.com/rjack, Oregon)"
task :publish_rdoc => [ :clean, :rerdoc ] do
  sh <<-SH
    aws s3 sync --acl public-read doc/ s3://rjack.gravitext.com/jdbc-postgres/
  SH
end
