# -*- ruby -*-

$LOAD_PATH << './lib'
require 'rjack-nekohtml/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.4'
require 'rjack-tarpit'

include RJack

t = TarPit.new( 'rjack-nekohtml', NekoHTML::VERSION, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps << [ 'rjack-xerces', '~> 2.9.1' ]
  h.rdoc_locations << "dekellum@rubyforge.org:/var/www/gforge-projects/rjack/nekohtml"
end

t.jars = [ "nekohtml-#{ NekoHTML::NEKOHTML_VERSION }.jar" ]

t.assembly_version = 1.0

file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

task :check_pom_deps do
  t.test_line_match( 'pom.xml',
                     %r[<version>#{ NekoHTML::NEKOHTML_VERSION }</version>] )
end

task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_deps, :check_history_version                      ]
task :tag  => [ :check_pom_deps, :check_history_version, :check_history_date ]
task :push => [                                          :check_history_date ]

t.define_tasks
