# -*- ruby -*-
#--
# Copyright (C) 2008-2009 David Kellum
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#++

require 'rubygems'

ENV['NODOT'] = "no thank you"
require 'hoe'

$LOAD_PATH << './lib'
require 'hc-httpclient/base'

ASSEMBLY = "target/httpclient-1.0-bin.dir"

desc "Update the Manifest with actual jars"
task :manifest => [ ASSEMBLY ] do
  out = File.new( 'Manifest.txt', 'w' )
  begin
    out.write <<END
History.txt
Manifest.txt
README.txt
Rakefile
pom.xml
assembly.xml
lib/hc-httpclient/base.rb
lib/hc-httpclient.rb
test/test_httpclient.rb
END
    out.puts( Dir.glob( File.join( ASSEMBLY, '*.jar' ) ).map do |jar|
                File.join( 'lib', 'hc-httpclient', File.basename( jar ) )
              end )
  ensure
    out.close
  end
end

file ASSEMBLY => [ 'pom.xml', 'assembly.xml' ] do
  sh( 'mvn package' )
end

JAR_FILES = File.new( 'Manifest.txt' ).readlines.map { |f| f.strip }\
.select { |f| f =~ /\.jar$/ }

JARS = JAR_FILES.map { |f| File.basename( f.strip ) }

JARS.each do |jar|
  file "lib/hc-httpclient/#{jar}" => [ ASSEMBLY ] do
    cp_r( File.join( ASSEMBLY, jar ), 'lib/hc-httpclient' )
  end
end
[ :gem, :test ].each { |t| task t => JAR_FILES }

task :mvn_clean do
  rm_f( JAR_FILES )
  sh( 'mvn clean' )
end

task :clean => :mvn_clean

task :tag do
  tag = "hc-httpclient-#{HC::HTTPClient::VERSION}"
  dname = File.dirname( __FILE__ )
  dname = '.' if Dir.getwd == dname
  sh( "git status --only #{dname}" ) do |ok,res|
    raise "Commit these changes before tagging." if ok #changes present
  end
  sh %{git tag -s -f -m "tag [#{tag}]" "#{tag}"}
end

hoe = Hoe.new( "hc-httpclient", HC::HTTPClient::VERSION ) do |p|
  p.developer( "David Kellum", "dek-oss@gravitext.com" )
  p.extra_deps     << [ 'slf4j',   '~> 1.5.8' ]
  p.extra_dev_deps << [ 'logback', '>= 0.9.16.1' ]
  p.rubyforge_name = "rjack"
end
