# -*- ruby -*-
#--
# Copyright (C) 2009 David Kellum
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#++

$LOAD_PATH << './lib'
require 'rjack-jets3t/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.2.0'
require 'rjack-tarpit'

include RJack

t = TarPit.new( 'rjack-jets3t', JetS3t::VERSION, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps     += [ [ 'rjack-slf4j',         '~> 1.5.8' ],
                        [ 'rjack-httpclient-3',  '~> 3.1.3' ],
                        [ 'rjack-commons-codec', '~> 1.4.0' ] ]
  h.extra_dev_deps <<   [ 'rjack-logback',       '>= 0.9.17']
  h.rubyforge_name  = "rjack"
  h.remote_rdoc_dir = "jets3t"
end

t.assembly_version = 1.0
t.jars = [ "jets3t-#{ JetS3t::JETS3T_VERSION }.jar" ]
file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

task :check_pom_deps do
  t.test_line_match( 'pom.xml',
                     %r[<version>#{ JetS3t::JETS3T_VERSION }</version>] )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_deps, :check_history_version                      ]
task :tag  => [ :check_pom_deps, :check_history_version, :check_history_date ]
task :push => [                                          :check_history_date ]

t.define_tasks
