# -*- ruby -*-
#--
# Copyright (C) 2009 David Kellum
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#++

$LOAD_PATH << './lib'
require 'rjack-jets3t/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.0.0'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'rjack-jets3t', RJack::JetS3t::VERSION )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps     += [ [ 'rjack-slf4j',         '~> 1.5.8' ],
                        [ 'rjack-httpclient',    '~> 3.1.3' ],
                        [ 'rjack-commons-codec', '~> 1.4.0' ] ]
  h.extra_dev_deps <<   [ 'rjack-logback',       '>= 0.9.17']
  h.rubyforge_name  = "rjack"
  h.remote_rdoc_dir = "jets3t"
end

t.assembly_version = 1.0
t.jars = [ "jets3t-#{ RJack::JetS3t::JETS3T_VERSION }.jar" ]
file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

t.define_tasks
