# -*- ruby -*-

require 'rubygems'
require 'bundler/setup'
require 'rjack-tarpit'

RJack::TarPit.new( 'rjack-protobuf' ) do |tp|

  tp.rdoc_destinations <<
    'dekellum@rubyforge.org:/var/www/gforge-projects/rjack/protobuf'
  tp.publish_rdoc_rsync_flags = %w[ -rL ]

end
