# -*- ruby -*-
#--
# Copyright (C) 2009 David Kellum
#
# See README.rdoc for license terms.
#++

$LOAD_PATH << './lib'
require 'rjack-jdom/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.1.0'
require 'rjack-tarpit'

include RJack

t = TarPit.new( 'rjack-jdom', JDOM::VERSION )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.rubyforge_name = "rjack"
  h.remote_rdoc_dir = "jdom"
end

t.jars = [ "jdom-#{ JDOM::JDOM_VERSION }.jar" ]

t.assembly_version = 1.0

file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

t.define_tasks
