# -*- ruby -*-

$LOAD_PATH << './lib'
require 'rjack-jdom/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.3.0'
require 'rjack-tarpit'

include RJack

t = TarPit.new( 'rjack-jdom', JDOM::VERSION, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.rubyforge_name = "rjack"
  h.remote_rdoc_dir = "jdom"
end

t.jars = [ "jdom-#{ JDOM::JDOM_VERSION }.jar" ]

t.assembly_version = 1.0

file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

task :check_pom_deps do
  t.test_line_match( 'pom.xml',
                     %r[<version>#{ JDOM::JDOM_VERSION }</version>] )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_deps, :check_history_version                      ]
task :tag  => [ :check_pom_deps, :check_history_version, :check_history_date ]
task :push => [                                          :check_history_date ]

t.define_tasks
