# -*- ruby -*-

require 'ostruct'
require 'erb'

rule( '.svg' => [ '.dot' ] ) do |t|
  sh "dot -Tsvg -o #{t.name} #{t.source}"
end

rule( '.png' => [ '.dot' ] ) do |t|
  sh "dot -Tpng -o #{t.name} #{t.source}"
end

def erb_generate( src, target, bindvar )
  puts "#{src} --generate--> #{target}"
  open( target, 'w' ) do |outf|
    outf.write( ERB.new( IO.read( src ) ).result( bindvar ) )
  end
end

file 'index.html' => [ 'index.erb', 'rjack.png' ] do
  id = `identify rjack.png`.strip
  m = id.match( /PNG (\d+)x(\d+)/ ) or raise id
  g = OpenStruct.new( :w => m[1], :h => m[2] )
  erb_generate( 'index.erb', 'index.html', binding )
end

FileList[ '*.dot' ].each do |d|
  task :default => d.gsub( /(\.dot)$/, '.svg' )
  task :default => d.gsub( /(\.dot)$/, '.png' )
end

task :default => [ 'index.html' ]
