# -*- ruby -*-
#--
# Copyright (C) 2008-2009 David Kellum
#
# Logback Ruby is free software: you can redistribute it and/or
# modify it under the terms of the
# {GNU Lesser General Public License}[http://www.gnu.org/licenses/lgpl.html]
# as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Logback Ruby is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#++

$LOAD_PATH << './lib'
require 'rjack-logback/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.0.0'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'rjack-logback', RJack::Logback::VERSION )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps << [ 'rjack-slf4j', '~> 1.5.8' ]
  h.rubyforge_name = "rjack"
  h.remote_rdoc_dir = "logback"
end

t.jars = %w{ core classic access }.map do |n|
  "logback-#{n}-#{ RJack::Logback::LOGBACK_VERSION }.jar"
end

file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

t.assembly_version = 1.0

t.define_tasks
