# -*- ruby -*-

$LOAD_PATH << './lib'
require 'rjack-qpid-client/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.3.0'
require 'rjack-tarpit'

include RJack

t = TarPit.new( 'rjack-qpid-client', QpidClient::VERSION, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )

  h.extra_deps   += [ [ 'rjack-jms',           '>= 1.0.0',  '< 1.2' ],
                      [ 'rjack-mina',          '~> 1.0.10'          ],
                      [ 'rjack-slf4j',         '>= 1.5.8',  '< 1.7' ] ]

  h.extra_dev_deps << [ 'rjack-logback',       '>= 0.9.18', '< 2.0' ]

  h.rdoc_locations << "dekellum@rubyforge.org:/var/www/gforge-projects/rjack/qpid-client"
end

t.jars = %w[ common client ].map do |mod|
  "qpid-#{mod}-#{ QpidClient::QPID_VERSION }.jar"
end

t.assembly_version = 1.0

file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

task :check_pom_deps do
  t.test_line_match( 'pom.xml',
                     %r[<version>#{ QpidClient::QPID_VERSION }</version>] )
end

task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_deps, :check_history_version                      ]
task :tag  => [ :check_pom_deps, :check_history_version, :check_history_date ]
task :push => [                                          :check_history_date ]

t.define_tasks
