# -*- ruby -*-

require 'rubygems'
require 'bundler/setup'
require 'rjack-tarpit'

RJack::TarPit.new( 'rjack-lucene' ) do |tp|

  tp.rdoc_destinations <<
    'dekellum@rubyforge.org:/var/www/gforge-projects/rjack/lucene'

end
