# -*- ruby -*-

require 'rubygems'
require 'bundler/setup'

require 'rjack-tarpit'

tp = RJack::TarPit.new( "rjack-tarpit" )

task :check_sample_version do
  tp.test_line_match( 'README.rdoc',
                      /^\s*gem.+#{ tp.spec.name }/,
                      /#{ tp.spec.version }/ )
end
[ :gem, :tag, :push ].each { |t| task t => :check_sample_version }

tp.define_tasks
