# -*- ruby -*-

$LOAD_PATH << './lib'
require 'slf4j/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.3.0'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'slf4j', SLF4JRedirect::VERSION, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps << [ 'rjack-slf4j', '~> 1.6.1' ]
  h.rdoc_locations << "dekellum@rubyforge.org:/var/www/gforge-projects/rjack/slf4j-redirect"
end

loaders = %w[ jul jul-to-slf4j jdk14 jcl-over-slf4j jcl
              log4j-over-slf4j log4j12 nop simple ]

t.generated_files = loaders.map { |adp| "lib/#{t.name}/#{adp}.rb" }

task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_history_version                      ]
task :tag  => [ :check_history_version, :check_history_date ]
task :push => [                         :check_history_date ]

t.define_tasks

loaders.each do |adapter|
  file "lib/#{t.name}/#{adapter}.rb" => [ "lib/#{t.name}/base.rb", 'Rakefile' ] do
    open( "lib/#{t.name}/#{adapter}.rb", 'w' ) do |out|
      out.write <<END
require 'slf4j'
require 'rjack-slf4j/#{adapter}'
END
    end
  end
end
