# -*- ruby -*-

require 'rubygems'
require 'bundler/setup'
require 'rjack-tarpit'

RJack::TarPit.new( 'rjack-httpclient-4' ) do |tp|

  tp.rdoc_destinations <<
    'dekellum@rubyforge.org:/var/www/gforge-projects/rjack/httpclient-4'

end
