# -*- ruby -*-
#--
# Copyright (C) 2008-2009 David Kellum
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#++

$LOAD_PATH << './lib'
require 'rjack-jetty/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.0.0'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'rjack-jetty', Jetty::VERSION )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_dev_deps << [ 'rjack-logback', '>= 0.9.17.1' ]
  h.rubyforge_name = "rjack"
end

t.jars =
  begin
    mods = %w{ jetty jetty-util jetty-rewrite-handler }
    l = mods.map { |n| "#{n}-#{ Jetty::JETTY_VERSION }.jar" }
    l << "servlet-api-#{ Jetty::SERVLET_API_VERSION }-#{ Jetty::SERVLET_API_DATE }.jar"
    l << 'rjack-jetty-1.0.jar'
    l
  end

file 'Manifest.txt' => [ "lib/#{t.name}/base.rb" ]

file 'webapps/test.war' => [ 'webapps/test/index.html',
                             'webapps/test/WEB-INF/web.xml' ] do
  sh( 'jar cvf webapps/test.war ' +
      '-C webapps/test index.html -C webapps/test WEB-INF/web.xml' )
end

t.generated_files = 'webapps/test.war'

t.assembly_version = 1.0
t.assembly_name = 'rjack-jetty' #FIXME: Make obsolete

t.define_tasks
